import { type NextPage } from "next";
import Head from "next/head";
import React, { useState } from "react";
import 'react-circular-progressbar/dist/styles.css';
// import DropdownMenu from '../components/dropdownMenu';
import { Item, useSelectState } from 'react-stately';
import DropdownMenu from '../components/newDropdownMenu';
import NewForm from '../components/newForm';
import SimpleForm from '../components/simpleForm';
import FormLayout from '../components/formLayout';

const Test: NextPage = () => {

    // function handleChange(object) {
    //     console.log(object.target.value)
    // }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/Portal_Icon.png" />
            </Head>
            {/* <FormLayout/> */}
            {/* <DropdownMenu>
                <option value="option1">Option 1</option>
                <option value="option2">Option 2</option>
                <option value="option3">Option 3</option>
            </DropdownMenu> */}
            {/* <NewForm>
                <input type="text" name="field1" label="Field 1" />
                <DropdownMenu name="field2" label="Field 2">
                    <option value="option1">Option 1</option>
                    <option value="option2">Option 2</option>
                    <option value="option3">Option 3</option>
                </DropdownMenu>
                <input type="text" name="field3" label="Field 3" />
                <input type="text" name="field4" label="Field 4" />
                <input type="text" name="field5" label="Field 5" />
            </NewForm> */}
            {/* <SimpleForm options={[
                { value: 'option1', label: 'Option 1' },
                { value: 'option2', label: 'Option 2' },
                { value: 'option3', label: 'Option 3' },
            ]} onChange={handleChange} /> */}



            {/* <DropdownMenu id="favorite-color" label="Favorite Color">
                <Item>Red</Item>
                <Item>Orange</Item>
                <Item>Yellow</Item>
                <Item>Green</Item>
                <Item>Blue</Item>
                <Item>Purple</Item>
                <Item>Black</Item>
                <Item>White</Item>
                <Item>Lime</Item>
                <Item>Fushsia</Item>
            </DropdownMenu> */}
            {/* <SearchDropdown label="Favorite Animal">
                <Item key="red panda">Red Panda</Item>
                <Item key="cat">Cat</Item>
                <Item key="dog">Dog</Item>
                <Item key="aardvark">Aardvark</Item>
                <Item key="kangaroo">Kangaroo</Item>
                <Item key="snake">Snake</Item>
            </SearchDropdown> */}
        </>
    )
}

export default Test