import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Sidebar from '../../components/sidebar'
import SortableTable from "../../components/sortableTable";

const Test: NextPage = () => {

    const tableData = [
        {
            name: "Nick",
            used: 24,
            captured: "Bath",
            rate: 90
        },
        {
            name: "Jack",
            used: 26,
            captured: "Bristol",
            rate: 80
        },
        {
            name: "Connor",
            used: 26,
            captured: "Bristol",
            rate: 70
        },
        {
            name: "Nick1",
            used: 24,
            captured: "Bath",
            rate: 90
        },
        {
            name: "Jack1",
            used: 26,
            captured: "Bristol",
            rate: 80
        },
        {
            name: "Connor1",
            used: 26,
            captured: "Bristol",
            rate: 70
        },
        {
            name: "Nick2",
            used: 24,
            captured: "Bath",
            rate: 90
        },
        {
            name: "Jack2",
            used: 26,
            captured: "Bristol",
            rate: 80
        },
        {
            name: "Connor2",
            used: 26,
            captured: "Bristol",
            rate: 70
        },
    ];

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="fixed bg-secondarygrey w-full h-full -z-10"></div>
            <div className="grid grid-cols-[auto_1fr]">
                <Sidebar />
                {/* <div className="fixed">
                        <div className="flex flex-col bg-secondaryblack w-screen h-screen p-4"></div>
                    </div> */}
                <div className="w-36"></div>
                <main className="w-full bg-secondarygrey">
                    <header className="grid grid-cols-[auto_1fr] grid-rows-1 bg-white shadow-md px-8 py-4">
                        <div>
                            <h5 className="text-2xl">[Client Name] Products</h5>
                            <h6>Portal / Products / Overview</h6>
                        </div>
                        <div className="flex gap-16 place-self-center">
                            <h6>Overview</h6>
                            <h6>Deliveries</h6>
                            <h6>Stock Checks</h6>
                        </div>
                    </header>
                    <div className="p-8">
                        <SortableTable data={tableData} />
                    </div>
                </main>
            </div>
        </>
    )
}

export default Test